apiVersion: v1
kind: Secret
metadata:
  name: scribe-demo-secrets
  namespace: scribe-demo
  labels:
    app: scribe-demo
type: Opaque
data:
  auth-url: aHR0cHM6Ly9hdXRob3JpemF0aW9uLmNlcm5lci5jb20vdGVuYW50cy9lYzI0NThmMi0xZTI0LTQxYzgtYjcxYi0wZTcwMWFmNzU4M2QvcHJvdG9jb2xzL29hdXRoMi9wcm9maWxlcy9zbWFydC12MS9wZXJzb25hcy9wcm92aWRlci9hdXRob3JpemU=
  token-url: aHR0cHM6Ly9hdXRob3JpemF0aW9uLmNlcm5lci5jb20vdGVuYW50cy9lYzI0NThmMi0xZTI0LTQxYzgtYjcxYi0wZTcwMWFmNzU4M2QvcHJvdG9jb2xzL29hdXRoMi9wcm9maWxlcy9zbWFydC12MS90b2tlbg==
  fhir-base: aHR0cHM6Ly9maGlyLWVoci1jb2RlLmNlcm5lci5jb20vcjQvZWMyNDU4ZjItMWUyNC00MWM4LWI3MWItMGU3MDFhZjc1ODNk
  client-id: Y2I0NDE2NDktMDYyMS00MGM4LTkwZjktZmJlNDIwZGQ3OWUw
  client-secret: a1I5NVJ0VUNlaWNrU0pfaFhsdk93WXdONGxBVk9ILTg=
  redirect-uri: aHR0cDovL2xvY2FsaG9zdDozMDAwL2xvZ2luLWNhbGxiYWNr
